name: esc_pos_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  image: ^4.1.7

dev_dependencies:
  import_sorter: ^4.6.0
  lint: ^2.0.0
  test: ^1.24.0

import_sorter:
  comments: false
